server:
  port: 9030
  servlet:
    context-path: /analyze
spring:
  profiles:
    active: dev
  application:
    name: analyzeservice
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
