Spring:
  application:
    name: gateway
  profiles:
    active:
  cloud:
    nacos:
      server-addr: localhost:8848 # Nacos地址
    gateway:
      discovery:
        locator:
          enabled: true
      routes: # 网关路由配置
        - id: core-service # 信息服务器
          uri: lb://coreservice
          predicates:
            - Path=/inc/**
        - id: search-service # 搜索服务器
          uri: lb://searchservice
          predicates:
            - Path=/_search/**
        - id: uaa-service # 认证服务器
          uri: lb://authservice
          predicates:
            - Path=/uaa/**
        - id: analyze-service # 个人财务分析服务器
          uri: lb://analyzeservice
          predicates:
            - Path=/analyze/**
        - id: stock-service # 股价及预测分析服务器
          uri: lb://stockservice
          predicates:
            - Path=/stock/**
server:
  port: 9000
spring:
  main:
    web-application-type: reactive


