spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/sfx_db?characterEncoding=utf-8&serverTimezone=UTC-8&zeroDateTimeBehavior=CONVERT_TO_NULL
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      server-addr: localhost:8848
    sentinel:
      web-context-unify: true
      transport:
        dashboard: localhost:8080
  application:
    name: coreservice
  main:
    allow-bean-definition-overriding: true
server:
  port: 9001
  servlet:
    context-path: /inc
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace