Spring:
  application:
    name: gateway
  profiles:
    active:
  cloud:
    nacos:
      server-addr: localhost:8848 # Nacos地址
    gateway:
      discovery:
        locator:
          enabled: true
      routes: # 网关路由配置
        - id: core-service # 路由id，自定义，只要唯一即可
          uri: lb://coreservice
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/inc/**
        - id: search-service
          uri: lb://searchservice
          predicates:
            - Path=/_search/**
server:
  port: 9000
spring:
  main:
    web-application-type: reactive