spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: authservice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456
    username: root
    url: jdbc:mysql://localhost:9980/sfx_user?characterEncoding=utf-8&serverTimezone=UTC-8&zeroDateTimeBehavior=CONVERT_TO_NULL
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848 # Nacos地址
server:
  port: 9020
  servlet:
    context-path: /uaa
logging:
  level:
    root: debug
    org.springframework: info